# Generated by Django 5.0.7 on 2024-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpf', models.FloatField()),
                ('NomeCompleto', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=75)),
                ('Telefone_celular', models.IntegerField()),
            ],
        ),
    ]
